# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(help_text='Access Level ID sequence.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name to identify the access level.', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date of creation.')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date of last modification.')),
                ('id', models.AutoField(help_text='Company ID sequence.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name or Customer.', max_length=45)),
                ('description', models.CharField(blank=True, help_text='Short description of company or customer.', max_length=500)),
                ('active', models.BooleanField(default=True, help_text='Is the company active?')),
                ('contact_address', models.CharField(help_text='Address to contact the account representatives.', max_length=200)),
                ('billing_contact_name', models.CharField(help_text='Name of the billing contact.', max_length=100)),
                ('billing_contact_email', models.EmailField(help_text='Email of the billing contact.', max_length=254)),
                ('billing_contact_phone', models.CharField(blank=True, help_text='Phone of the billing contact.', max_length=20)),
                ('technical_contact_name', models.CharField(help_text='Name of the technical contact.', max_length=100)),
                ('technical_contact_email', models.EmailField(help_text='Email of the technical contact.', max_length=254)),
                ('technical_contact_phone', models.CharField(blank=True, help_text='Phone of the technical contact.', max_length=20)),
                ('alternate_contact_name', models.CharField(blank=True, help_text='Name of the alternate contact.', max_length=100)),
                ('alternate_contact_email', models.EmailField(blank=True, help_text='Email of the alternate contact.', max_length=254)),
                ('alternate_contact_phone', models.CharField(blank=True, help_text='Phone of the alternate contact.', max_length=20)),
                ('access_level', models.ForeignKey(blank=True, help_text='Access Level required to see this company.', on_delete=django.db.models.deletion.CASCADE, to='oslayer.AccessLevel')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(help_text='User ID sequence.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name to identify the user.', max_length=45)),
                ('email', models.CharField(help_text='Contact e-mail.', max_length=45)),
                ('password', models.CharField(blank=True, help_text='Password set by the user.', max_length=45)),
                ('security_question', models.CharField(help_text='Security question to be used on the event of password lose or user ID lose.', max_length=100)),
                ('security_question_answer', models.CharField(help_text='Answer to the security question to be used on the event of password lose or user ID lose.', max_length=100)),
                ('created_on', models.DateTimeField(help_text='Date of creation.')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether the user is confirmed or not. Default is FALSE.')),
                ('external_id', models.CharField(blank=True, help_text='Openstack ID for this user.', max_length=50)),
                ('account_main_user', models.BooleanField(default=False, help_text='Whether the user is the main one for its Account. Default is FALSE.')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the record.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oslayer.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='modified_by',
            field=models.ForeignKey(help_text='User who last updated the record.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oslayer.User'),
        ),
    ]
